extends RefCounted


static func run(test: TestSupport) -> void:
	var player := PlayerData.from_save_data({"potions": {"green_potion": [
		{"quality": 0.8, "remaining_dose": 0.1, "instance_uid": "low"},
		{"quality": 1.2, "remaining_dose": 1.0, "instance_uid": "high"},
	]}})
	var service := PotionInventoryService.new(player)
	service.setup(player)
	test.expect_float_close(service.get_total_dose(&"green_potion"), 1.1, 0.001, "Total dose keeps partial instances.")
	var reservation := service.reserve_dose(&"green_potion", 0.25)
	test.expect(reservation != null, "A cross-instance dose can be reserved.")
	test.expect_equal(reservation.allocations[0]["instance_uid"], "low", "Lower quality is consumed first.")
	test.expect_float_close(float(reservation.allocations[1]["dose"]), 0.15, 0.001, "Reservation spans the next instance.")
	test.expect(service.reserve_dose(&"green_potion", 0.9) == null, "Reserved dose cannot be double-booked.")
	service.cancel_reservation(reservation)
	test.expect_float_close(service.get_available_dose(&"green_potion"), 1.1, 0.001, "Cancel releases reserved dose.")
	reservation = service.reserve_dose(&"green_potion", 0.25)
	var payload := service.commit_reservation(reservation)
	test.expect_float_close(float(payload.get("quality", 0.0)), 1.04, 0.001, "Consumed attributes are dose weighted.")
	test.expect_equal(service.get_instances(&"green_potion").size(), 1, "Near-zero source instances are removed.")
	player.potions[&"green_potion"].append({"potion_id": "green_potion", "instance_uid": "manual", "remaining_dose": 0.5, "quality": 0.2})
	service.set_throw_order(&"green_potion", ["high", "manual"])
	reservation = service.reserve_dose(&"green_potion", 0.1)
	test.expect_equal(reservation.allocations[0]["instance_uid"], "high", "Manual UID order overrides quality order.")
	service.cancel_reservation(reservation)
	var migrated := PlayerData.from_save_data({"potions": {"red_potion": [{"quality": 1.0}]}})
	test.expect(not str(migrated.potions[&"red_potion"][0].get("instance_uid", "")).is_empty(), "Legacy instances receive stable UIDs.")
	test.expect_float_close(float(migrated.potions[&"red_potion"][0].get("remaining_dose", 0.0)), 1.0, 0.001, "Legacy instances receive full dose.")
	var partial_player := PlayerData.from_save_data({"potions": {"blue_potion": [{"instance_uid": "single", "remaining_dose": 1.0}]}})
	var partial_service := PotionInventoryService.new(partial_player)
	partial_service.setup(partial_player)
	var partial_reservation := partial_service.reserve_dose(&"blue_potion", 0.25)
	partial_service.commit_reservation(partial_reservation)
	test.expect_float_close(float(partial_service.get_instances(&"blue_potion")[0]["remaining_dose"]), 0.75, 0.001, "A single instance supports partial consumption.")
	partial_player.unlock_potion_slot(2)
	partial_player.unlock_throwable_potion(&"purple_potion")
	test.expect(partial_player.equip_potion(3, &"purple_potion"), "An unlocked slot accepts an equippable potion type.")
	partial_player.select_potion_slot(3)
	var restored := PlayerData.from_save_data(partial_player.to_save_data())
	test.expect_equal(restored.potion_slot_count, 5, "Unlocked potion slots survive save migration.")
	test.expect_equal(restored.equipped_potion_ids[3], &"purple_potion", "Equipped potion IDs survive save migration.")
	test.expect_equal(restored.selected_potion_slot, 3, "Selected potion slot survives save migration.")
	var red_definition: PotionData = load("res://shared/definitions/data/potions/red_potion.tres")
	test.expect_equal(service.calculate_instance_sale_value(red_definition, {"remaining_dose": 0.25, "price_multiplier": 1.0}), roundi(red_definition.base_price * 0.25), "Partially used potions sell in proportion to remaining dose.")
	var new_result := NightResult.new()
	new_result.produced_potions = {&"green_potion": [{"instance_uid": "new-low", "remaining_dose": 1.0, "quality": 0.15}]}
	player.apply_night_result(new_result)
	test.expect_equal(player.potion_throw_orders[&"green_potion"][0], "new-low", "New low-quality instances enter the default order at a reasonable position.")
